[package]
name = "oas3"
version = "0.2.1"
authors = ["Rob Ede <robjtede@icloud.com>", "softprops <d.tangren@gmail.com>"]
edition = "2018"
description = "Structures and tools to parse, navigate and validate OpenAPI v3 specifications."
readme = "README.md"
repository = "https://github.com/robjtede/oas3-rs"
license = "MIT"
keywords = ["oas3", "openapi", "swagger", "api", "validation"]
categories = ["data-structures", "development-tools::testing", "parsing"]

[features]
default = ["validation"]
validation = []
conformance = ["validation", "reqwest", "prettytable-rs", "colored"]
multiple-files=[]

[dependencies]
bytes = "0.5"
derive_more = "0.99"
futures-util = "0.3"
http = "0.2"
once_cell = "1"
log = "0.4"
regex = "1"
semver = "0.11"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.8"
url = { version = "2", features = ["serde"] }
# conformance
colored = { version = "2", optional = true }
prettytable-rs = { version = "0.8", optional = true }
reqwest = { version = "0.10", optional = true, features = ["json"] }

[dev-dependencies]
color-eyre = "0.5"
dotenv = "0.15"
eyre = "0.6"
maplit = "1"
pretty_assertions = "0.6"
pretty_env_logger = "0.4"
tokio = { version = "0.2", features = ["full"] }

[[example]]
name = "conformance"
required-features = ["conformance"]
